name: Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Exécute le workflow tous les jours à minuit (UTC).
  workflow_dispatch: # Permet de lancer manuellement l'animation.

jobs:
  generate:
    name: Generate Snake Animation
    runs-on: ubuntu-latest

    steps:
      # Cloner le dépôt
      - name: Clone Repository
        uses: actions/checkout@v3

      # Configuration du Snake Generator
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          # Spécifie où l'animation sera générée
          output: dist/github-contribution-grid-snake.svg

      # Publier le fichier généré dans le dépôt
      - name: Push Snake Animation to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
